# This file was automagically generated by mbed.org. For more information,
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded
# but has been modified to include files not available on mbed

# not used
# ./fsl_can/common/fsl_flexcan_common.o \
# ./fsl_can/src/fsl_flexcan_driver.o \
# ./k64f_CAN/fsl_flexcan_irq.o \

#GCC_BIN = /home/wiley/Solvehicle/k64f/tools/GNUARM/gcc-arm-none-eabi-4_9-2015q1/bin/
GCC_BIN = /opt/GNUARM/gcc-arm-none-eabi-4_8-2014q2/bin/
#GCC_BIN = /opt/GNUARM/gcc-arm-none-eabi-4_9-2015q1/bin/
PROJECT = k64fCANdrive
OBJECTS = \
./mbed-src/targets/cmsis/TARGET_Freescale/TARGET_MCU_K64F/TOOLCHAIN_GCC_ARM/startup_MK64F12.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/TARGET_M4/TOOLCHAIN_GCC/HAL_CM4.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/TARGET_M4/TOOLCHAIN_GCC/SVC_Table.o \
./mbed-src/targets/cmsis/TARGET_Freescale/TARGET_MCU_K64F/cmsis_nvic.o \
./mbed-src/targets/cmsis/TARGET_Freescale/TARGET_MCU_K64F/system_MK64F12.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/analogin_api.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/analogout_api.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/gpio_api.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/gpio_irq_api.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/i2c_api.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/pinmap.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/port_api.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/pwmout_api.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/rtc_api.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/serial_api.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/sleep.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/spi_api.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/us_ticker.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/common/phyksz8081/fsl_phy_driver.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/drivers/clock/fsl_clock_manager.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/drivers/enet/src/fsl_enet_irq.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/drivers/pit/common/fsl_pit_common.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/drivers/pit/src/fsl_pit_driver.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/drivers/pit/src/fsl_pit_irq.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/adc/fsl_adc_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/can/fsl_flexcan_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/dac/fsl_dac_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/dmamux/fsl_dmamux_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/dspi/fsl_dspi_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/edma/fsl_edma_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/enet/fsl_enet_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/flextimer/fsl_ftm_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/gpio/fsl_gpio_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/i2c/fsl_i2c_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/llwu/fsl_llwu_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/lptmr/fsl_lptmr_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/lpuart/fsl_lpuart_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/mcg/fsl_mcg_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/mcg/fsl_mcg_hal_modes.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/mpu/fsl_mpu_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/osc/fsl_osc_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/pdb/fsl_pdb_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/pit/fsl_pit_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/pmc/fsl_pmc_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/port/fsl_port_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/rcm/fsl_rcm_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/rtc/fsl_rtc_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/sai/fsl_sai_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/sdhc/fsl_sdhc_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/sim/fsl_sim_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/smc/fsl_smc_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/uart/fsl_uart_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/wdog/fsl_wdog_hal.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/utilities/src/fsl_misc_utilities.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/utilities/src/fsl_os_abstraction_mbed.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_MCU_K64F/MK64F12/fsl_clock_K64F12.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_MCU_K64F/MK64F12/fsl_sim_hal_K64F12.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PeripheralPins.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_MCU_K64F/TARGET_FRDM/crc.o \
./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_MCU_K64F/TARGET_FRDM/mbed_overrides.o \
./mbed-src/common/assert.o \
./mbed-src/common/board.o \
./mbed-src/common/error.o \
./mbed-src/common/gpio.o \
./mbed-src/common/lp_ticker_api.o \
./mbed-src/common/mbed_interface.o \
./mbed-src/common/pinmap_common.o \
./mbed-src/common/rtc_time.o \
./mbed-src/common/semihost_api.o \
./mbed-src/common/ticker_api.o \
./mbed-src/common/us_ticker_api.o \
./mbed-src/common/wait_api.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/HAL_CM.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/rt_CMSIS.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/rt_Event.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/rt_List.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/rt_Mailbox.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/rt_MemBox.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/rt_Mutex.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/rt_Robin.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/rt_Semaphore.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/rt_System.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/rt_Task.o \
./mbed-rtos/rtx/TARGET_CORTEX_M/rt_Time.o \
 ./utsvt/main.o \
 ./utsvt/K64FID.o \
 ./SEEED_CAN/seeed_can_api.o \
 ./SEEED_CAN/seeed_can.o \
 ./SEEED_CAN/seeed_can_spi.o \
 ./utsvt/svtCAN.o \
 ./utsvt/svtK64FCAN.o \
 ./utsvt/svtSensor.o \
 ./utsvt/FXOS8700CQ.o \
 ./utsvt/svtGPSsensor.o \
 ./utsvt/svtTPMSsensor.o \
 ./utsvt/svtMPPTsensor.o \
 ./utsvt/svtIMUsensor.o \
 ./utsvt/svtGAPsensor.o \
 ./utsvt/CirQueue.o \
 ./utsvt/BufferedSerial.o \
 ./utsvt/BufferedFMF.o \
 ./utsvt/BufferedNGM.o \
 ./utsvt/svtDASHsensor.o \
 ./utsvt/svtBPSsensor.o \
 ./utsvt/GPSQueue.o \
 ./utsvt/GreenLEDsensor.o \
 ./utsvt/svtSensorMgr.o \
 ./utsvt/svtSysState.o \
 ./utsvt/svtNGMsensor.o \
 ./utsvt/svtContactor.o \
 ./utsvt/svtCNTRLstate.o \
 ./utsvt/svtCNTRLsensor.o \
 ./utsvt/svtSwitch.o \
 ./utsvt/svtAnalogInFilter.o \
 ./utsvt/svtUSB.o \
 ./utsvt/USBK64F.o \
 ./k64f_CAN/k64f_CAN.o \
 ./k64f_CAN/k64f_can_api.o \
./mbed-src/common/BusIn.o \
./mbed-src/common/BusInOut.o \
./mbed-src/common/BusOut.o \
./mbed-src/common/CAN.o \
./mbed-src/common/CallChain.o \
./mbed-src/common/Ethernet.o \
./mbed-src/common/FileBase.o \
./mbed-src/common/FileLike.o \
./mbed-src/common/FilePath.o \
./mbed-src/common/FileSystemLike.o \
./mbed-src/common/I2C.o \
./mbed-src/common/I2CSlave.o \
./mbed-src/common/InterruptIn.o \
./mbed-src/common/InterruptManager.o \
./mbed-src/common/LocalFileSystem.o \
./mbed-src/common/RawSerial.o \
./mbed-src/common/SPI.o \
./mbed-src/common/SPISlave.o \
./mbed-src/common/Serial.o \
./mbed-src/common/SerialBase.o \
./mbed-src/common/Stream.o \
./mbed-src/common/Ticker.o \
./mbed-src/common/Timeout.o \
./mbed-src/common/Timer.o \
./mbed-src/common/TimerEvent.o \
./mbed-src/common/retarget.o \
./mbed-rtos/rtos/Mutex.o \
./mbed-rtos/rtos/RtosTimer.o \
./mbed-rtos/rtos/Semaphore.o \
./mbed-rtos/rtos/Thread.o \
./USBDevice/USBAudio/USBAudio.o \
./USBDevice/USBDevice/USBDevice.o \
./USBDevice/USBDevice/USBHAL_EFM32.o \
./USBDevice/USBDevice/USBHAL_KL25Z.o \
./USBDevice/USBDevice/USBHAL_LPC11U.o \
./USBDevice/USBDevice/USBHAL_LPC17.o \
./USBDevice/USBDevice/USBHAL_LPC40.o \
./USBDevice/USBDevice/USBHAL_Maxim.o \
./USBDevice/USBDevice/USBHAL_RZ_A1H.o \
./USBDevice/USBDevice/USBHAL_STM32F4.o \
./USBDevice/USBHID/USBHID.o  \
./USBDevice/USBHID/USBKeyboard.o \
./USBDevice/USBHID/USBMouse.o \
./USBDevice/USBHID/USBMouseKeyboard.o \
./USBDevice/USBMIDI/USBMIDI.o \
./USBDevice/USBMSD/USBMSD.o \
./USBDevice/USBSerial/USBSerial.o

SYS_OBJECTS =

INCLUDE_PATHS = -I. -I ./k64f_CAN -I ./SEEED_CAN -I./mbed-rtos -I./mbed-rtos/rtos -I./utsvt \
 -I./mbed-rtos/rtx\
 -I./mbed-rtos/rtx/TARGET_CORTEX_M \
 -I./mbed-rtos/rtx/TARGET_CORTEX_M/TARGET_M4 \
 -I./mbed-rtos/rtx/TARGET_CORTEX_M/TARGET_M4/TOOLCHAIN_GCC -I./mbed-src -I./mbed-src/common \
 -I./mbed-src/hal \
 -I./mbed-src/api \
 -I./mbed-src/targets \
 -I./mbed-src/targets/cmsis /\
 -I./mbed-src/targets/cmsis/TARGET_Freescale -I./mbed-src/targets/cmsis/TARGET_Freescale/TARGET_MCU_K64F -I./mbed-src/targets/cmsis/TARGET_Freescale/TARGET_MCU_K64F/TOOLCHAIN_GCC_ARM -I./mbed-src/targets/hal -I./mbed-src/targets/hal/TARGET_Freescale -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_MCU_K64F -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_MCU_K64F/TARGET_FRDM -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_MCU_K64F/device -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_MCU_K64F/device/device -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_MCU_K64F/device/device/MK64F12 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_MCU_K64F/device/MK64F12 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_MCU_K64F/MK64F12 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/utilities \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/utilities/src \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/common  \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/common/phyksz8081 \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/llwu \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/edma \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/sim \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/pdb \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/adc \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/rcm \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/port \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/osc \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/enet\
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/can\
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/pit\
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/mpu\
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/uart \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/dmamux \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/flextimer \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/lptmr \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/dspi \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/wdog \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/sdhc \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/lpuart \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/rtc \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/sai \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/mcg \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/dac \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/pmc \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/smc \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/gpio \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/i2c \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/hal/port \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/drivers \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/drivers/enet \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/drivers/enet/src \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/drivers/pit \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/drivers/pit/common \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/drivers/pit/src \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/drivers/interrupt \
 -I./mbed-src/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_KPSDK_CODE/drivers/clock \
 -I./fsl_can/ \
 -I./fsl_can/common \
 -I./fsl_can/src \
-I./mbed-src/common \
-I./mbed-rtos \
-I./mbed-rtos/rtos \
-I./mbed-rtos/rtx \
-I./mbed-rtos/rtx/TARGET_CORTEX_M \
-I./mbed-rtos/rtx/TARGET_CORTEX_M/TARGET_M4 \
-I./mbed-rtos/rtx/TARGET_CORTEX_M/TARGET_M4/TOOLCHAIN_GCC \
-I./USBDevice \
-I./USBDevice/USBAudio \
-I./USBDevice/USBDevice \
-I./USBDevice/USBHID \
-I./USBDevice/USBMIDI \
-I./USBDevice/USBSerial


LIBRARY_PATHS = 
LIBRARIES = 
LINKER_SCRIPT = ./mbed-src/targets/cmsis/TARGET_Freescale/TARGET_MCU_K64F/TOOLCHAIN_GCC_ARM/K64FN1M0xxx12.ld

###############################################################################
AS      = $(GCC_BIN)arm-none-eabi-as
CC      = $(GCC_BIN)arm-none-eabi-gcc
CPP     = $(GCC_BIN)arm-none-eabi-g++
LD      = $(GCC_BIN)arm-none-eabi-gcc
OBJCOPY = $(GCC_BIN)arm-none-eabi-objcopy
OBJDUMP = $(GCC_BIN)arm-none-eabi-objdump
SIZE 	= $(GCC_BIN)arm-none-eabi-size

ifeq ($(HARDFP),1)
	FLOAT_ABI = hard
else
	FLOAT_ABI = softfp
endif


CPU = -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=$(FLOAT_ABI) 
CC_FLAGS = $(CPU) -c -g -fno-common -fmessage-length=0 -Wall -Wextra -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -MMD -MP
CC_SYMBOLS = -DTARGET_KPSDK_MCUS -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM -DTOOLCHAIN_GCC -DCPU_MK64FN1M0VMD12 -DTARGET_FRDM -DTARGET_CORTEX_M -DMBED_BUILD_TIMESTAMP=1447243473.16 -D__FPU_PRESENT=1 -DTARGET_KPSDK_CODE -DTARGET_M4 -D__MBED__=1 -DTARGET_K64F -DTARGET_Freescale -D__CORTEX_M4 -DFSL_RTOS_MBED -DTARGET_MCU_K64F -DARM_MATH_CM4 


LD_FLAGS = $(CPU) -Wl,--gc-sections --specs=nano.specs -u _printf_float -u _scanf_float
LD_FLAGS += -Wl,-Map=$(PROJECT).map,--cref
LD_SYS_LIBS = -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys

ifeq ($(DEBUG), 1)
  CC_FLAGS += -DDEBUG -O0
else
  CC_FLAGS += -DNDEBUG -Os
endif

.PHONY: all clean lst size

all: $(PROJECT).bin $(PROJECT).hex size


clean:
	rm -f $(PROJECT).bin $(PROJECT).elf $(PROJECT).hex $(PROJECT).map $(PROJECT).lst $(OBJECTS) $(DEPS)

.asm.o:
	$(CC) $(CPU) -c -x assembler-with-cpp -o $@ $<
.s.o:
	$(CC) $(CPU) -c -x assembler-with-cpp -o $@ $<
.S.o:
	$(CC) $(CPU) -c -x assembler-with-cpp -o $@ $<
.c.o:
	$(CC)  $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu99   $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	$(CPP) $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu++98 -fno-rtti $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS)
	$(LD) $(LD_FLAGS) -T$(LINKER_SCRIPT) $(LIBRARY_PATHS) -o $@ $^ $(LIBRARIES) $(LD_SYS_LIBS) $(LIBRARIES) $(LD_SYS_LIBS)
	$(SIZE) $@

$(PROJECT).bin: $(PROJECT).elf
	@$(OBJCOPY) -O binary $< $@
	cp $(PROJECT).bin ../deploy

$(PROJECT).hex: $(PROJECT).elf
	@$(OBJCOPY) -O ihex $< $@

$(PROJECT).lst: $(PROJECT).elf
	@$(OBJDUMP) -Sdh $< > $@

lst: $(PROJECT).lst

size:
	$(SIZE) -A -d -t $(PROJECT).elf

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
