#!/bin/bash
#
#    Script to initialize the Raspberry Pis used in the UTSVT Solar Vehicle Data Acquistion and Display System.
#
## VARIABLES ##
CURDIR="$PWD"  
CDPATH=:$HOME/SolarCarProject		# Directory to git repository
DISPLAY="Display"			# Name of display side directory (in git repo)
DAQ="Acquisition"			# Name of car side directory (in git repo)

## DISPLAY FUNCTION ##
display() {
	echo "Running Pit RPI scripts . . ."
	cd "$DISPLAY"
	chmod +x ./display.sh		
	./display.sh			# Run display side main script
	#echo "$PWD"
	cd "$CURDIR"
}

## IN-CAR FUNCTION ##
incar() {
	echo "Running Car RPI scripts . . ."
	# If this fails, it is likely necessary to perform a 'sudo apt-get upgrade' and 'sudo apt-get update'
	cd "$DAQ"
	chmod +x ./can.sh
	./can.sh
	#echo "$PWD"
	cd "$CURDIR"
}

## VALIDATE ARGUMENTS ##
if [ $# -ne 1 ]; then
	echo "Usage: $0 {pit|car|run|quit}" >&2
	exit 1
fi

## HANDLE ARGUMENTS ##
case "$1" in
	# Run display scripts
	pit)
		display
		exit 0
		;;
	# Run in-car scripts
	car)
		incar
		exit 0
		;;
	run)
		echo "Waiting for data . . ."
		cd "$DISPLAY"
		chmod +x ./run.sh		
		./run.sh			# Run python logging script
		#echo "$PWD"
		cd "$CURDIR" 
		exit 0
		;;
	quit)
		echo "Ending python logging script . . ."
		cd "$DISPLAY"
		chmod +x ./quit.sh		
		./quit.sh			# Kill python logging script
		#echo "$PWD"
		cd "$CURDIR" 
		echo ". . . safe to disconnect power."
		exit 0
		;;
	# Show usage
	*)
		echo "Usage: $0 {pit|car|run|quit}" >&2
		exit 1	
	;;
esac

## END ##
