#!/bin/bash
#
#    Script to initialize the Raspberry Pis used in the UTSVT Solar Vehicle Data Acquistion and Display System.
#    USAGE: TBD
#
## VARIABLES ##
CURDIR="$PWD"  
CDPATH=:$HOME/SolarCarProject		# Directory to git repository
DISPLAY="Display"			# Name of display side directory (in git repo)
DAQ="new_acquisition"			# Name of pit side directory (in git repo)

## DISPLAY FUNCTION ##
display() {
	echo "Running Pit RPI scripts . . ."
	cd "$DISPLAY"
	chmod +x ./display.sh		
	./display.sh			# Run display side main script
	#echo "$PWD"
	cd "$CURDIR"
}

## IN-CAR FUNCTION ##
incar() {
	echo "Running Car RPI scripts . . ."
	# TODO: Car scripts
	# James wants an overall update/upgrade
	# install can-utils package
	# purge fake-hwclock package
	# append to /boot/config.txt
		## utsvt RPi3 config
		## for RTC
		# dtparam=i2c_arm=on
		# dtoverlay=i2c-rtc,ds3231
		##can bus
		# dtoverlay=mcp2515-can0
		# dtparam=oscillator=16000000
		# dtparam=interrupt=13
		# dtparam=spimaxfrequency=100000
		##to use serial port /dev/ttyAMM0 for BN055
		# dtoverlay=pi3-disable-bt
		# enable_uart=1
	# Reboot.
	cd "$DAQ"
	echo "$PWD"
	cd "$CURDIR"
}

## VALIDATE ARGUMENTS ##
if [ $# -ne 1 ]; then
	echo "Usage: $0 {pit|car}" >&2
	exit 1
fi

## HANDLE ARGUMENTS ##
case "$1" in
	# Run display scripts
	pit)
		display
		exit 0
		;;
	# Run in-car scripts
	car)
		incar
		exit 0
		;;
	# Show usage
	*)
		echo "Usage: $0 {pit|car}" >&2
		exit 1	
	;;
esac

## END ##
