import datetime
import random
import sys
import time

from influxdb import InfluxDBClient

# Set this variables, influxDB should be localhost on Pi
host = "localhost"
port = 8086
user = "admin"
password = "password123"

# The database we created
dbname = "my_db"
# Sample period (s)
interval = 1

# Allow user to set session and runno via args otherwise auto-generate
if len(sys.argv) > 1:
    if (len(sys.argv) < 3):
        print "Must define session and runNo!!"
        sys.exit()
    else:
        session = sys.argv[1]
        runNo = sys.argv[2]
else:
    session = "dev"
    now = datetime.datetime.now()
    runNo = now.strftime("%Y%m%d%H%M")

print "Session: ", session
print "runNo: ", runNo

# Create the InfluxDB object
client = InfluxDBClient(host, port, user, password, dbname)

# Run until keyboard out
try:
    while True:
        # Generate timestamp and random VSENSE value.
        vsense = random.randint(0, 100)
        iso = time.ctime()

        json_body = [
            {
                "measurement": session,
                "tags": {
                    "run": runNo
                },
                "time": iso,
                "fields": {
                    "vsense1" : vsense + 1,
                    "vsense2" : vsense + 2,
                    "vsense3" : vsense + 3,
                    "vsense4" : vsense + 4,
                    "vsense5" : vsense + 5,
                    "vsense6" : vsense + 6,
                    "vsense7" : vsense + 7,
                    "vsense8" : vsense + 8,
                    "vsense9" : vsense + 9,
                    "vsense10" : vsense + 10,
                    "vsense11" : vsense + 11,
                    "vsense12" : vsense + 12,
                    "vsense13" : vsense + 13,
                    "vsense14" : vsense + 14,
                    "vsense15" : vsense + 15,
                    "vsense16" : vsense + 16,
                    "vsense17" : vsense + 17,
                    "vsense18" : vsense + 18,
                    "vsense19" : vsense + 19,
                    "vsense20" : vsense + 20,
                    "vsense21" : vsense + 21,
                    "vsense22" : vsense + 10,
                    "vsense23" : vsense + 11,
                    "vsense24" : vsense + 12,
                    "vsense25" : vsense + 13,
                    "vsense26" : vsense + 14,
                    "vsense27" : vsense + 15,
                    "vsense28" : vsense + 16,
                    "vsense29" : vsense + 17,
                    "vsense30" : vsense + 18,
                    "vsense31" : vsense + 19,
                    "vsense32" : vsense + 20,
                    "vsense33" : vsense + 21,
                    "vsense34" : vsense + 10,
                    "vsense35" : vsense + 11,
                    "vsense36" : vsense + 12,
                    "vsense37" : vsense + 13,
                    "vsense38" : vsense + 14,
                    "vsense39" : vsense + 15,
                    "vsense40" : vsense + 16,
                    "vsense41" : vsense + 17,
                    "vsense42" : vsense + 18,
                    "vsense43" : vsense + 19,
                    "vsense44" : vsense + 20,
                    "vsense45" : vsense + 21,
                    "vsense46" : vsense + 10,
                    "vsense47" : vsense + 11,
                    "vsense48" : vsense + 12,
                    "vsense49" : vsense + 13,
                    "vsense50" : vsense + 14,
                    "vsense51" : vsense + 15,
                    "vsense52" : vsense + 16,
                    "vsense53" : vsense + 17,
                    "vsense54" : vsense + 18,
                    "vsense55" : vsense + 19,
                    "vsense56" : vsense + 14,
                    "vsense57" : vsense + 15,
                    "vsense58" : vsense + 16,
                    "vsense59" : vsense + 17,
                    "vsense60" : vsense + 16,
                    "vsense61" : vsense + 17,
                    "vsense62" : vsense + 18,
                    "vsense63" : vsense + 19,
                    "vsense64" : vsense + 20,
                    "vsense65" : vsense + 21,
                    "vsense66" : vsense + 10,
                    "vsense67" : vsense + 11,
                    "vsense68" : vsense + 12,
                    "vsense69" : vsense + 13,
                    "vsense70" : vsense + 14,
                    "vsense71" : vsense + 15,
                    "vsense72" : vsense + 16,
                    "vsense73" : vsense + 17,
                    "vsense74" : vsense + 18,
                    "vsense75" : vsense + 19,
                    "vsense76" : vsense + 14,
                    "vsense77" : vsense + 15,
                    "vsense78" : vsense + 16,
                    "vsense79" : vsense + 17,
                    "vsense80" : vsense + 16,
                    "vsense81" : vsense + 17,
                    "vsense82" : vsense + 18,
                    "vsense83" : vsense + 19,
                    "vsense84" : vsense + 20,
                    "vsense85" : vsense + 21,
                    "vsense86" : vsense + 10,
                    "vsense87" : vsense + 11,
                    "vsense88" : vsense + 12,
                    "vsense89" : vsense + 13,
                    "vsense90" : vsense + 14,
                    "vsense91" : vsense + 15,
                    "vsense92" : vsense + 16,
                    "vsense93" : vsense + 17,
                    "vsense94" : vsense + 18,
                    "vsense95" : vsense + 19,
                    "vsense96" : vsense + 14,
                    "vsense97" : vsense + 15,
                    "vsense98" : vsense + 16,
                    "vsense99" : vsense + 17,
					"vsense100" : vsense + 18,
                    "vsense101" : vsense + 1,
                    "vsense102" : vsense + 2,
                    "vsense103" : vsense + 3,
                    "vsense104" : vsense + 4,
                    "vsense105" : vsense + 5,
                    "vsense106" : vsense + 6,
                    "vsense107" : vsense + 7,
                    "vsense108" : vsense + 8,
                    "vsense109" : vsense + 9,
                    "vsense110" : vsense + 10,
                    "vsense111" : vsense + 11,
                    "vsense112" : vsense + 12,
                    "vsense113" : vsense + 13,
                    "vsense114" : vsense + 14,
                    "vsense115" : vsense + 15,
                    "vsense116" : vsense + 16,
                    "vsense117" : vsense + 17,
                    "vsense118" : vsense + 18,
                    "vsense119" : vsense + 19,
                    "vsense120" : vsense + 20,
                    "vsense121" : vsense + 21,
                    "vsense122" : vsense + 10,
                    "vsense123" : vsense + 11,
                    "vsense124" : vsense + 12,
                    "vsense125" : vsense + 13,
                    "vsense126" : vsense + 14,
                    "vsense127" : vsense + 15,
                    "vsense128" : vsense + 16,
                    "vsense129" : vsense + 17,
                    "vsense130" : vsense + 18,
                    "vsense131" : vsense + 19,
                    "vsense132" : vsense + 20,
                    "vsense133" : vsense + 21,
                    "vsense134" : vsense + 10,
                    "vsense135" : vsense + 11,
                    "vsense136" : vsense + 12,
                    "vsense137" : vsense + 13,
                    "vsense138" : vsense + 14,
                    "vsense139" : vsense + 15,
                    "vsense140" : vsense + 16,
                    "vsense141" : vsense + 17,
                    "vsense142" : vsense + 18,
                    "vsense143" : vsense + 19,
                    "vsense144" : vsense + 20,
                    "vsense145" : vsense + 21,
                    "vsense146" : vsense + 10,
                    "vsense147" : vsense + 11,
                    "vsense148" : vsense + 12,
                    "vsense149" : vsense + 13,
                    "vsense150" : vsense + 14,
                    "vsense151" : vsense + 15,
                    "vsense152" : vsense + 16,
                    "vsense153" : vsense + 17,
                    "vsense154" : vsense + 18,
                    "vsense155" : vsense + 19,
                    "vsense156" : vsense + 14,
                    "vsense157" : vsense + 15,
                    "vsense158" : vsense + 16,
                    "vsense159" : vsense + 17,
                    "vsense160" : vsense + 16,
                    "vsense161" : vsense + 17,
                    "vsense162" : vsense + 18,
                    "vsense163" : vsense + 19,
                    "vsense164" : vsense + 20,
                    "vsense165" : vsense + 21,
                    "vsense166" : vsense + 10,
                    "vsense167" : vsense + 11,
                    "vsense168" : vsense + 12,
                    "vsense169" : vsense + 13,
                    "vsense170" : vsense + 14,
                    "vsense171" : vsense + 15,
                    "vsense172" : vsense + 16,
                    "vsense173" : vsense + 17,
                    "vsense174" : vsense + 18,
                    "vsense175" : vsense + 19,
                    "vsense176" : vsense + 14,
                    "vsense177" : vsense + 15,
                    "vsense178" : vsense + 16,
                    "vsense179" : vsense + 17,
                    "vsense180" : vsense + 16,
                    "vsense181" : vsense + 17,
                    "vsense182" : vsense + 18,
                    "vsense183" : vsense + 19,
                    "vsense184" : vsense + 20,
                    "vsense185" : vsense + 21,
                    "vsense186" : vsense + 10,
                    "vsense187" : vsense + 11,
                    "vsense188" : vsense + 12,
                    "vsense189" : vsense + 13,
                    "vsense190" : vsense + 14,
                    "vsense191" : vsense + 15,
                    "vsense192" : vsense + 16,
                    "vsense193" : vsense + 17,
                    "vsense194" : vsense + 18,
                    "vsense195" : vsense + 19,
                    "vsense196" : vsense + 14,
                    "vsense197" : vsense + 15,
                    "vsense198" : vsense + 16,
                    "vsense199" : vsense + 17,
                    "vsense201" : vsense + 1,
                    "vsense202" : vsense + 2,
                    "vsense203" : vsense + 3,
                    "vsense204" : vsense + 4,
                    "vsense205" : vsense + 5,
                    "vsense206" : vsense + 6,
                    "vsense207" : vsense + 7,
                    "vsense208" : vsense + 8,
                    "vsense209" : vsense + 9,
                    "vsense210" : vsense + 10,
                    "vsense211" : vsense + 11,
                    "vsense212" : vsense + 12,
                    "vsense213" : vsense + 13,
                    "vsense214" : vsense + 14,
                    "vsense215" : vsense + 15,
                    "vsense216" : vsense + 16,
                    "vsense217" : vsense + 17,
                    "vsense218" : vsense + 18,
                    "vsense219" : vsense + 19,
                    "vsense220" : vsense + 20,
                    "vsense221" : vsense + 21,
                    "vsense222" : vsense + 10,
                    "vsense223" : vsense + 11,
                    "vsense224" : vsense + 12,
                    "vsense225" : vsense + 13,
                    "vsense226" : vsense + 14,
                    "vsense227" : vsense + 15,
                    "vsense228" : vsense + 16,
                    "vsense229" : vsense + 17,
                    "vsense230" : vsense + 18,
                    "vsense231" : vsense + 19,
                    "vsense232" : vsense + 20,
                    "vsense233" : vsense + 21,
                    "vsense234" : vsense + 10,
                    "vsense235" : vsense + 11,
                    "vsense236" : vsense + 12,
                    "vsense237" : vsense + 13,
                    "vsense238" : vsense + 14,
                    "vsense239" : vsense + 15,
                    "vsense240" : vsense + 16,
                    "vsense241" : vsense + 17,
                    "vsense242" : vsense + 18,
                    "vsense243" : vsense + 19,
                    "vsense244" : vsense + 20,
                    "vsense245" : vsense + 21,
                    "vsense246" : vsense + 10,
                    "vsense247" : vsense + 11,
                    "vsense248" : vsense + 12,
                    "vsense249" : vsense + 13,
                    "vsense250" : vsense + 14,
                    "vsense251" : vsense + 15,
                    "vsense252" : vsense + 16,
                    "vsense253" : vsense + 17,
                    "vsense254" : vsense + 18,
                    "vsense255" : vsense + 19,
                    "vsense256" : vsense + 14,
                    "vsense257" : vsense + 15,
                    "vsense258" : vsense + 16,
                    "vsense259" : vsense + 17,
                    "vsense260" : vsense + 16,
                    "vsense261" : vsense + 17,
                    "vsense262" : vsense + 18,
                    "vsense263" : vsense + 19,
                    "vsense264" : vsense + 20,
                    "vsense265" : vsense + 21,
                    "vsense266" : vsense + 10,
                    "vsense267" : vsense + 11,
                    "vsense268" : vsense + 12,
                    "vsense269" : vsense + 13,
                    "vsense270" : vsense + 14,
                    "vsense271" : vsense + 15,
                    "vsense272" : vsense + 16,
                    "vsense273" : vsense + 17,
                    "vsense274" : vsense + 18,
                    "vsense275" : vsense + 19,
                    "vsense276" : vsense + 14,
                    "vsense277" : vsense + 15,
                    "vsense278" : vsense + 16,
                    "vsense279" : vsense + 17,
                    "vsense280" : vsense + 16,
                    "vsense281" : vsense + 17,
                    "vsense282" : vsense + 18,
                    "vsense283" : vsense + 19,
                    "vsense284" : vsense + 20,
                    "vsense285" : vsense + 21,
                    "vsense286" : vsense + 10,
                    "vsense287" : vsense + 11,
                    "vsense288" : vsense + 12,
                    "vsense289" : vsense + 13,
                    "vsense290" : vsense + 14,
                    "vsense291" : vsense + 15,
                    "vsense292" : vsense + 16,
                    "vsense293" : vsense + 17,
                    "vsense294" : vsense + 18,
                    "vsense295" : vsense + 19,
                    "vsense296" : vsense + 14,
                    "vsense297" : vsense + 15,
                    "vsense298" : vsense + 16,
                    "vsense299" : vsense + 17,
					"vsense300" : vsense + 18,
                    "vsense301" : vsense + 1,
                    "vsense302" : vsense + 2,
                    "vsense303" : vsense + 3,
                    "vsense304" : vsense + 4,
                    "vsense305" : vsense + 5,
                    "vsense306" : vsense + 6,
                    "vsense307" : vsense + 7,
                    "vsense308" : vsense + 8,
                    "vsense309" : vsense + 9,
                    "vsense310" : vsense + 10,
                    "vsense311" : vsense + 11,
                    "vsense312" : vsense + 12,
                    "vsense313" : vsense + 13,
                    "vsense314" : vsense + 14,
                    "vsense315" : vsense + 15,
                    "vsense316" : vsense + 16,
                    "vsense317" : vsense + 17,
                    "vsense318" : vsense + 18,
                    "vsense319" : vsense + 19,
                    "vsense320" : vsense + 20,
                    "vsense321" : vsense + 21,
                    "vsense322" : vsense + 10,
                    "vsense323" : vsense + 11,
                    "vsense324" : vsense + 12,
                    "vsense325" : vsense + 13,
                    "vsense326" : vsense + 14,
                    "vsense327" : vsense + 15,
                    "vsense328" : vsense + 16,
                    "vsense329" : vsense + 17,
                    "vsense330" : vsense + 18,
                    "vsense331" : vsense + 19,
                    "vsense332" : vsense + 20,
                    "vsense333" : vsense + 21,
                    "vsense334" : vsense + 10,
                    "vsense335" : vsense + 11,
                    "vsense336" : vsense + 12,
                    "vsense337" : vsense + 13,
                    "vsense338" : vsense + 14,
                    "vsense339" : vsense + 15,
                    "vsense340" : vsense + 16,
                    "vsense341" : vsense + 17,
                    "vsense342" : vsense + 18,
                    "vsense343" : vsense + 19,
                    "vsense344" : vsense + 20,
                    "vsense345" : vsense + 21,
                    "vsense346" : vsense + 10,
                    "vsense347" : vsense + 11,
                    "vsense348" : vsense + 12,
                    "vsense349" : vsense + 13,
                    "vsense350" : vsense + 14,
                    "vsense351" : vsense + 15,
                    "vsense352" : vsense + 16,
                    "vsense353" : vsense + 17,
                    "vsense354" : vsense + 18,
                    "vsense355" : vsense + 19,
                    "vsense356" : vsense + 14,
                    "vsense357" : vsense + 15,
                    "vsense358" : vsense + 16,
                    "vsense359" : vsense + 17,
                    "vsense360" : vsense + 16,
                    "vsense361" : vsense + 17,
                    "vsense362" : vsense + 18,
                    "vsense363" : vsense + 19,
                    "vsense364" : vsense + 20,
                    "vsense365" : vsense + 21,
                    "vsense366" : vsense + 10,
                    "vsense367" : vsense + 11,
                    "vsense368" : vsense + 12,
                    "vsense369" : vsense + 13,
                    "vsense370" : vsense + 14,
                    "vsense371" : vsense + 15,
                    "vsense372" : vsense + 16,
                    "vsense373" : vsense + 17,
                    "vsense374" : vsense + 18,
                    "vsense375" : vsense + 19,
                    "vsense376" : vsense + 14,
                    "vsense377" : vsense + 15,
                    "vsense378" : vsense + 16,
                    "vsense379" : vsense + 17,
                    "vsense380" : vsense + 16,
                    "vsense381" : vsense + 17,
                    "vsense382" : vsense + 18,
                    "vsense383" : vsense + 19,
                    "vsense384" : vsense + 20,
                    "vsense385" : vsense + 21,
                    "vsense386" : vsense + 10,
                    "vsense387" : vsense + 11,
                    "vsense388" : vsense + 12,
                    "vsense389" : vsense + 13,
                    "vsense390" : vsense + 14,
                    "vsense391" : vsense + 15,
                    "vsense392" : vsense + 16,
                    "vsense393" : vsense + 17,
                    "vsense394" : vsense + 18,
                    "vsense395" : vsense + 19,
                    "vsense396" : vsense + 14,
                    "vsense397" : vsense + 15,
                    "vsense398" : vsense + 16,
                    "vsense399" : vsense + 17,
                    "vsense401" : vsense + 1,
                    "vsense402" : vsense + 2,
                    "vsense403" : vsense + 3,
                    "vsense404" : vsense + 4,
                    "vsense405" : vsense + 5,
                    "vsense406" : vsense + 6,
                    "vsense407" : vsense + 7,
                    "vsense408" : vsense + 8,
                    "vsense409" : vsense + 9,
                    "vsense410" : vsense + 10,
                    "vsense411" : vsense + 11,
                    "vsense412" : vsense + 12,
                    "vsense413" : vsense + 13,
                    "vsense414" : vsense + 14,
                    "vsense415" : vsense + 15,
                    "vsense416" : vsense + 16,
                    "vsense417" : vsense + 17,
                    "vsense418" : vsense + 18,
                    "vsense419" : vsense + 19,
                    "vsense420" : vsense + 20,
                    "vsense421" : vsense + 21,
                    "vsense422" : vsense + 10,
                    "vsense423" : vsense + 11,
                    "vsense424" : vsense + 12,
                    "vsense425" : vsense + 13,
                    "vsense426" : vsense + 14,
                    "vsense427" : vsense + 15,
                    "vsense428" : vsense + 16,
                    "vsense429" : vsense + 17,
                    "vsense430" : vsense + 18,
                    "vsense431" : vsense + 19,
                    "vsense432" : vsense + 20,
                    "vsense433" : vsense + 21,
                    "vsense434" : vsense + 10,
                    "vsense435" : vsense + 11,
                    "vsense436" : vsense + 12,
                    "vsense437" : vsense + 13,
                    "vsense438" : vsense + 14,
                    "vsense439" : vsense + 15,
                    "vsense440" : vsense + 16,
                    "vsense441" : vsense + 17,
                    "vsense442" : vsense + 18,
                    "vsense443" : vsense + 19,
                    "vsense444" : vsense + 20,
                    "vsense445" : vsense + 21,
                    "vsense446" : vsense + 10,
                    "vsense447" : vsense + 11,
                    "vsense448" : vsense + 12,
                    "vsense449" : vsense + 13,
                    "vsense450" : vsense + 14,
                    "vsense451" : vsense + 15,
                    "vsense452" : vsense + 16,
                    "vsense453" : vsense + 17,
                    "vsense454" : vsense + 18,
                    "vsense455" : vsense + 19,
                    "vsense456" : vsense + 14,
                    "vsense457" : vsense + 15,
                    "vsense458" : vsense + 16,
                    "vsense459" : vsense + 17,
                    "vsense460" : vsense + 16,
                    "vsense461" : vsense + 17,
                    "vsense462" : vsense + 18,
                    "vsense463" : vsense + 19,
                    "vsense464" : vsense + 20,
                    "vsense465" : vsense + 21,
                    "vsense466" : vsense + 10,
                    "vsense467" : vsense + 11,
                    "vsense468" : vsense + 12,
                    "vsense469" : vsense + 13,
                    "vsense470" : vsense + 14,
                    "vsense471" : vsense + 15,
                    "vsense472" : vsense + 16,
                    "vsense473" : vsense + 17,
                    "vsense474" : vsense + 18,
                    "vsense475" : vsense + 19,
                    "vsense476" : vsense + 14,
                    "vsense477" : vsense + 15,
                    "vsense478" : vsense + 16,
                    "vsense479" : vsense + 17,
                    "vsense480" : vsense + 16,
                    "vsense481" : vsense + 17,
                    "vsense482" : vsense + 18,
                    "vsense483" : vsense + 19,
                    "vsense484" : vsense + 20,
                    "vsense485" : vsense + 21,
                    "vsense486" : vsense + 10,
                    "vsense487" : vsense + 11,
                    "vsense488" : vsense + 12,
                    "vsense489" : vsense + 13,
                    "vsense490" : vsense + 14,
                    "vsense491" : vsense + 15,
                    "vsense492" : vsense + 16,
                    "vsense493" : vsense + 17,
                    "vsense494" : vsense + 18,
                    "vsense495" : vsense + 19,
                    "vsense496" : vsense + 14,
                    "vsense497" : vsense + 15,
                    "vsense498" : vsense + 16,
                    "vsense499" : vsense + 17
                }
            }
        ]

        # Write JSON to InfluxDB
        client.write_points(json_body)
        # Wait for next sample
        time.sleep(interval)

except KeyboardInterrupt:
    pass
